# Generated by Django 2.2.16 on 2020-09-09 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
